services:
  web:
    build: .
    command: sh -c "gunicorn phishtest.phishtest.wsgi:application --bind 0.0.0.0:8000 & nginx -g 'daemon off;'"
    volumes:
      - .:/PhishTest
    ports:
      - "8080:8000"
    env_file:
      - ./.env
    environment:
      - CSRF_TRUSTED_ORIGINS=http://localhost:8080
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

volumes:
  postgres_data:
