# Generated by Django 5.1.4 on 2025-01-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_course_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
