# Generated by Django 5.1.4 on 2025-01-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_answer_created_at_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='score',
            field=models.FloatField(),
        ),
    ]
